//// OPERATION MCU CODE ////
// Institution: California State University Northridge
// Author: Svarun Soda
// Thesis Advisor: Jeffrey Wiegley, Ph.D.
// Degree: Master of Science in Computer Science
// Thesis Date: May 2026
// Language: C++
// Target System: "Teensy 4.1" by PJRC

//// INCLUDES ////

#include <SD.h>

//// GLOBAL VARIALBES ////

const uint8_t OscillatorNum = 6;                                      // number of used oscillator modules in the system
const uint8_t TDVNum = OscillatorNum / 2;                            // number of TDVs used in the system (corresponds to half the number of used oscillators)
const uint8_t TDVOperationNum = 5;

const uint8_t PINS_ENABLE[OscillatorNum] = {23, 20, 17, 0, 3, 5};     // pins for enabling the oscillator modules (digital outputs from MCU)
const uint8_t PINS_PAUSE[OscillatorNum] = {22, 19, 16, 1, 4, 6};      // pins for pausing the oscillator modules' oscillations (digital outputs from MCU)
const uint8_t PINS_SIGNAL[OscillatorNum] = {21, 18, 14, 41, 40, 39};  // pins for reading the clock signals generated by the oscillator modules (digital inputs to MCU)
const uint8_t PINS_UNUSED[2] = {7, 8};
const uint8_t PIN_RNG = 15;

const uint8_t TDVOscillators[TDVNum][2] = {{0, 1}, {2, 3}, {4, 5}}; // oscillator assignments for each TDV used in the system
const float Tolerance = 0.1;                                          // precision of overall system
const uint32_t OscillatorOperatingCycles = 1200000;
const uint32_t OperationTestStarts[TDVOperationNum] = {0, 5999, 3999, 9909, 8049};
const uint32_t OperationTestBatchEnds[TDVOperationNum] = {0, 6000, 4000, 9910, 8050};
const uint32_t OperationTestSteps[TDVOperationNum] = {0, 1, 1, 1, 1};
const uint32_t OperationRunsPerTest = 5;
const uint32_t EvaluationRollingAverage = 1;
const uint32_t FrequencyLogIters = 2000;
const uint32_t OperationEvaluationPhaseLogIters = 3000;

// DO NOT EDIT

float TDVTargetValues[TDVNum];
bool TDVTrackingMask[TDVNum];
uint8_t TDVResultStatus[TDVNum];

#define SDCardConfig SdioConfig(FIFO_SDIO)
FsFile LogFile;

//// MAIN FUNCIONS ////

// function called upon MCU startup
// initializes digital pins, serial lines, initializes TDV conditions & the clock cycle counter register
FLASHMEM void setup() 
{
  // initializing serial lines to computer...
  Serial.begin(9600);

  // initializing all digital pins...
  for (uint8_t i = 0; i < OscillatorNum; i++)
  {
    DigitalPinInit(PINS_ENABLE[i], OUTPUT);
    DigitalPinInit(PINS_PAUSE[i], OUTPUT);
    DigitalPinInit(PINS_SIGNAL[i], INPUT);
  }
  for (uint8_t i = 0; i < 2; i++)
  {
    DigitalPinInit(PINS_UNUSED[i], INPUT);
  }
  DigitalPinInit(PIN_RNG, INPUT);

  // initializing TDV conditions...
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVDisable(i);
    TDVUnpause(i);
    TDVTargetValues[i] = -1.0;
    TDVTrackingMask[i] = true;
    TDVResultStatus[i] = 0;
  }

  // initializing CPU cycle counter register...
  Serial.println("initializing CPU cycle counter register...");
  CPUCyclesInit();
  delay(1000);

  // initializing random number geneator...
  Serial.println("initializing random number generator...");
  RNGInit();
  delay(1000);

  // waiting with initial TDV conditions...
  Serial.println("waiting with initial TDV conditions...");
  delay(10000);
}

// function called repeatedly during MCU operation
// contains topmost-level operation & evaluation logic
FLASHMEM void loop() 
{
  Serial.println("\n---- PROGRAM STARTED ----\n");

  // unpausing & enabling all TDVs...
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVUnpause(i);
    TDVEnable(i);
  }

  delay(120000);

  ProgramRun(OscillatorOperatingCycles, FrequencyLogIters, OperationEvaluationPhaseLogIters, OperationRunsPerTest, EvaluationRollingAverage, Tolerance);

  // when the testing session is concluded, all TDVs are disabled...
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVDisable(i);
  }
  Serial.println("\n---- PROGRAM FINISHED ----");
  while (true) {delay(1000);}
}

//// PROGRAM FUNCTIONS ////

inline void ProgramRun(const uint32_t operatingCycles, const uint32_t frequencyLogIters, const uint32_t phaseLogIters, const uint32_t runsPerOperationTest, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_ProgramRun_Start}@
{
  Serial.println("running program:\n" + ProgramToString(operatingCycles, frequencyLogIters, phaseLogIters, runsPerOperationTest, rollingAverage, tolerance));

  // testing TDV frequencies...
  EvaluateOscillatorFrequencies(frequencyLogIters, operatingCycles, rollingAverage);
  
  // testing TDV setting & resetting (1)...
  EvaluateTDVSet(phaseLogIters, operatingCycles, rollingAverage, tolerance);

  // testing TDV copy (2)...
  EvaluateTDVCopy(phaseLogIters, operatingCycles, runsPerOperationTest, rollingAverage, tolerance);

  // testing TDV invert (3)...
  EvaluateTDVInversion(phaseLogIters, operatingCycles, runsPerOperationTest, rollingAverage, tolerance);

  // testing TDV addition (4)...
  EvaluateTDVAddition(phaseLogIters, operatingCycles, runsPerOperationTest, rollingAverage, tolerance);

  // testing TDV subtraction (5)...
  EvaluateTDVSubtraction(phaseLogIters, operatingCycles, runsPerOperationTest, rollingAverage, tolerance);
} //@\label{line:operationMcu_ProgramRun_End}@

// function that converts a set of evaluation program parameters to a printable string
inline String ProgramToString(const uint32_t operatingCycles, const uint32_t frequencyLogIters, const uint32_t phaseLogIters, const uint32_t runsPerOperationTest, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_ProgramToString_Start}@
{
  String str = "";

  str += "\toscillators: " + String(OscillatorNum);
  str += "\n\tTDVs: {";
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    str += "{" + String(TDVOscillators[i][0]) + ", " + String(TDVOscillators[i][1]) + "}";
    if (i < (TDVNum - 1))
      str += ", ";
  }
  str += "}\n\toperating cycles: " + String(operatingCycles);
  str += "\n\tfrequency evaluation iterations: " + String(frequencyLogIters);
  str += "\n\tphase evaluation iterations: " + String(phaseLogIters);
  str += "\n\toperation test starts: {";
  for (uint8_t i = 0; i < TDVOperationNum; i++)
  {
    str += String(OperationTestStarts[i]);
    if (i < (TDVOperationNum - 1))
      str += ", ";
  }
  str += "}\n\toperation test batch ends: {";
  for (uint8_t i = 0; i < TDVOperationNum; i++)
  {
    str += String(OperationTestBatchEnds[i]);
    if (i < (TDVOperationNum - 1))
      str += ", ";
  }
  str += "}\n\toperation test steps: {";
  for (uint8_t i = 0; i < TDVOperationNum; i++)
  {
    str += String(OperationTestSteps[i]);
    if (i < (TDVOperationNum - 1))
      str += ", ";
  }
  str += "}\n\toperation test runs: " + String(runsPerOperationTest);
  str += "\n\trolling average: " + String(rollingAverage);
  str += "\n\ttolerance: " + String(tolerance);

  return str;
} //@\label{line:operationMcu_ProgramToString_End}@

// function that evaluates the TDV subtraction operation
// repeatedly executes the subtraction operation over a set of pre-determined inputs & compares their expected outputs
inline void EvaluateTDVSubtraction(const uint32_t phaseLogSaveIters, const uint32_t operatingCycles, const uint32_t runsPerDurationTest, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_EvaluateTDVSubtraction_Start}@
{
  String data, dataHeader;
  uint32_t currOperationDuration, startTime;
  float testValue1, testValue2, tdv3ValueExpected;

  const uint8_t operationIdx = 4;

  // defining all test operand values...
  const uint32_t testValueNum = 91;
  const float testValues[testValueNum][2] = {
    {0.1, 0.3},
    {0.1, 0.35},
    {0.1, 0.4},
    {0.1, 0.45},
    {0.1, 0.5},
    {0.1, 0.55},
    {0.1, 0.6},
    {0.1, 0.65},
    {0.1, 0.7},
    {0.1, 0.75},
    {0.1, 0.8},
    {0.1, 0.85},
    {0.1, 0.9},
    {0.15, 0.35},
    {0.15, 0.4},
    {0.15, 0.45},
    {0.15, 0.5},
    {0.15, 0.55},
    {0.15, 0.6},
    {0.15, 0.65},
    {0.15, 0.7},
    {0.15, 0.75},
    {0.15, 0.8},
    {0.15, 0.85},
    {0.15, 0.9},
    {0.2, 0.4},
    {0.2, 0.45},
    {0.2, 0.5},
    {0.2, 0.55},
    {0.2, 0.6},
    {0.2, 0.65},
    {0.2, 0.7},
    {0.2, 0.75},
    {0.2, 0.8},
    {0.2, 0.85},
    {0.2, 0.9},
    {0.25, 0.45},
    {0.25, 0.5},
    {0.25, 0.55},
    {0.25, 0.6},
    {0.25, 0.65},
    {0.25, 0.7},
    {0.25, 0.75},
    {0.25, 0.8},
    {0.25, 0.85},
    {0.25, 0.9},
    {0.3, 0.5},
    {0.3, 0.55},
    {0.3, 0.6},
    {0.3, 0.65},
    {0.3, 0.7},
    {0.3, 0.75},
    {0.3, 0.8},
    {0.3, 0.85},
    {0.3, 0.9},
    {0.35, 0.55},
    {0.35, 0.6},
    {0.35, 0.65},
    {0.35, 0.7},
    {0.35, 0.75},
    {0.35, 0.8},
    {0.35, 0.85},
    {0.35, 0.9},
    {0.4, 0.6},
    {0.4, 0.65},
    {0.4, 0.7},
    {0.4, 0.75},
    {0.4, 0.8},
    {0.4, 0.85},
    {0.4, 0.9},
    {0.45, 0.65},
    {0.45, 0.7},
    {0.45, 0.75},
    {0.45, 0.8},
    {0.45, 0.85},
    {0.45, 0.9},
    {0.5, 0.7},
    {0.5, 0.75},
    {0.5, 0.8},
    {0.5, 0.85},
    {0.5, 0.9},
    {0.55, 0.75},
    {0.55, 0.8},
    {0.55, 0.85},
    {0.55, 0.9},
    {0.6, 0.8},
    {0.6, 0.85},
    {0.6, 0.9},
    {0.65, 0.85},
    {0.65, 0.9},
    {0.7, 0.9}
  };

  const uint32_t operationDurationStart = OperationTestStarts[operationIdx];
  const uint32_t operationDurationBatchEnd = OperationTestBatchEnds[operationIdx];
  const uint32_t operationDurationStep = OperationTestSteps[operationIdx];
  const uint32_t operationDurationTestNum = floor((operationDurationBatchEnd - operationDurationStart) / operationDurationStep);
  
  uint32_t timestampBuff[operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];
  uint32_t cycleDiffBuff[TDVNum][operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];

  Serial.println("\n---- EVALUATING SUBTRACTION ----");

  // running tests for all test operand values...
  for (uint32_t i = 0; i < testValueNum; i++)
  {
    testValue1 = testValues[i][0];
    testValue2 = testValues[i][1];
    tdv3ValueExpected = testValue2 - testValue1;

    Serial.println("\n-- SUBTRACTION TEST #" + String(i + 1) + " --");
    Serial.println("TDV 1 = " + String(testValue1) + " | TDV 2 = " + String(testValue2) + " | TDV 3 = TDV 2 - TDV 1 = " + String(tdv3ValueExpected));
    delay(1000);
    
    TDVsTrackingShowAll();
    TDVResultSet(0, 0);
    TDVResultSet(1, 1);
    TDVResultSet(2, 2);
    
    for (uint32_t j = 0; j < operationDurationTestNum; j++)
    {
      currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

      for (uint32_t k = 0; k < runsPerDurationTest; k++)
      {
        // resetting all TDVs...
        TDVResetAll(operatingCycles, rollingAverage, tolerance);
        delay(RNGGet(1, 10));
        // setting TDV 1 to it's respective value in the test operand sequence...
        TDVSet(0, testValue1, operatingCycles, rollingAverage, tolerance);
        // setting TDV 2 to it's respective value in the test operand sequence...
        TDVSet(1, testValue2, operatingCycles, rollingAverage, tolerance);
        // subtracting TDV 2 from TDV 1 & storing the result in TDV 3...
        TDVsSubtract(0, 1, 2, operatingCycles, currOperationDuration, rollingAverage, tolerance);
        // tracking all TDVs & storing result to SD card...
        if (phaseLogSaveIters > 0)
        {
          startTime = micros();
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            timestampBuff[j][k][l] = micros() - startTime;
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
                cycleDiffBuff[m][j][k][l] = TDVGetCycles(m, operatingCycles, rollingAverage);
            }
          }
        }
      }
    }

    if (phaseLogSaveIters > 0)
    {
      SDCardInit();
      SDLogFileNew("log_phase_" + String(operatingCycles) + "_" + String(operationIdx) + "_" + String(i + 1) + ".txt");

      for (uint32_t j = 0; j < operationDurationTestNum; j++)
      {
        currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

        for (uint32_t k = 0; k < runsPerDurationTest; k++)
        {
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
              {
                data = String(operatingCycles) + "|" + 
                        String(operationIdx) + "|" +
                        String(currOperationDuration) + "|" +
                        String(i + 1) + "|" +
                        String(k + 1) + "|" +
                        String(m) + "|" +
                        String(TDVResultStatus[m]) + "|" +
                        String((uint32_t)round(TDVTargetValues[m] * operatingCycles)) + "|" +
                        String(l) + "|" + 
                        String(timestampBuff[j][k][l]) + "|" + 
                        String(cycleDiffBuff[m][j][k][l]);
                SDLogFileWriteLn(data);
              }
            }
          }
        }
      }

      SDLogFileClose();
      SDCardClose();
    }
  }
} //@\label{line:operationMcu_EvaluateTDVSubtraction_End}@

// function that evaluates the TDV addition operation
// repeatedly executes the addition operation over a set of pre-determined inputs & compares their expected outputs
inline void EvaluateTDVAddition(const uint32_t phaseLogSaveIters, const uint32_t operatingCycles, const uint32_t runsPerDurationTest, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_EvaluateTDVAddition_Start}@
{
  String data, dataHeader;
  uint32_t currOperationDuration, startTime;
  float testValue1, testValue2, tdv3ValueExpected;

  const uint8_t operationIdx = 3;

  // defining all test operand values...
  const uint32_t testValueNum = 91;
  const float testValues[testValueNum][2] = {
    {0.1, 0.1},
    {0.1, 0.15},
    {0.1, 0.2},
    {0.1, 0.25},
    {0.1, 0.3},
    {0.1, 0.35},
    {0.1, 0.4},
    {0.1, 0.45},
    {0.1, 0.5},
    {0.1, 0.55},
    {0.1, 0.6},
    {0.1, 0.65},
    {0.1, 0.7},
    {0.15, 0.1},
    {0.15, 0.15},
    {0.15, 0.2},
    {0.15, 0.25},
    {0.15, 0.3},
    {0.15, 0.35},
    {0.15, 0.4},
    {0.15, 0.45},
    {0.15, 0.5},
    {0.15, 0.55},
    {0.15, 0.6},
    {0.15, 0.65},
    {0.2, 0.1},
    {0.2, 0.15},
    {0.2, 0.2},
    {0.2, 0.25},
    {0.2, 0.3},
    {0.2, 0.35},
    {0.2, 0.4},
    {0.2, 0.45},
    {0.2, 0.5},
    {0.2, 0.55},
    {0.2, 0.6},
    {0.25, 0.1},
    {0.25, 0.15},
    {0.25, 0.2},
    {0.25, 0.25},
    {0.25, 0.3},
    {0.25, 0.35},
    {0.25, 0.4},
    {0.25, 0.45},
    {0.25, 0.5},
    {0.25, 0.55},
    {0.3, 0.1},
    {0.3, 0.15},
    {0.3, 0.2},
    {0.3, 0.25},
    {0.3, 0.3},
    {0.3, 0.35},
    {0.3, 0.4},
    {0.3, 0.45},
    {0.3, 0.5},
    {0.35, 0.1},
    {0.35, 0.15},
    {0.35, 0.2},
    {0.35, 0.25},
    {0.35, 0.3},
    {0.35, 0.35},
    {0.35, 0.4},
    {0.35, 0.45},
    {0.4, 0.1},
    {0.4, 0.15},
    {0.4, 0.2},
    {0.4, 0.25},
    {0.4, 0.3},
    {0.4, 0.35},
    {0.4, 0.4},
    {0.45, 0.1},
    {0.45, 0.15},
    {0.45, 0.2},
    {0.45, 0.25},
    {0.45, 0.3},
    {0.45, 0.35},
    {0.5, 0.1},
    {0.5, 0.15},
    {0.5, 0.2},
    {0.5, 0.25},
    {0.5, 0.3},
    {0.55, 0.1},
    {0.55, 0.15},
    {0.55, 0.2},
    {0.55, 0.25},
    {0.6, 0.1},
    {0.6, 0.15},
    {0.6, 0.2},
    {0.65, 0.1},
    {0.65, 0.15},
    {0.7, 0.1}
  };

  const uint32_t operationDurationStart = OperationTestStarts[operationIdx];
  const uint32_t operationDurationBatchEnd = OperationTestBatchEnds[operationIdx];
  const uint32_t operationDurationStep = OperationTestSteps[operationIdx];
  const uint32_t operationDurationTestNum = floor((operationDurationBatchEnd - operationDurationStart) / operationDurationStep);
  
  uint32_t timestampBuff[operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];
  uint32_t cycleDiffBuff[TDVNum][operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];

  Serial.println("\n---- EVALUATING ADDITION ----");

  // running tests for all test operand values...
  for (uint32_t i = 0; i < testValueNum; i++)
  {
    testValue1 = testValues[i][0];
    testValue2 = testValues[i][1];
    tdv3ValueExpected = testValue1 + testValue2;

    Serial.println("\n-- ADDITION TEST #" + String(i + 1) + " --");
    Serial.println("TDV 1 = " + String(testValue1) + " | TDV 2 = " + String(testValue2) + " | TDV 3 = TDV 1 + TDV 2 = " + String(tdv3ValueExpected));
    delay(1000);
    
    TDVsTrackingShowAll();
    TDVResultSet(0, 0);
    TDVResultSet(1, 1);
    TDVResultSet(2, 2);
    
    for (uint32_t j = 0; j < operationDurationTestNum; j++)
    {
      currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

      for (uint32_t k = 0; k < runsPerDurationTest; k++)
      {
        // resetting all TDVs...
        TDVResetAll(operatingCycles, rollingAverage, tolerance);
        delay(RNGGet(1, 10));
        // setting TDV 1 to it's respective value in the test operand sequence...
        TDVSet(0, testValue1, operatingCycles, rollingAverage, tolerance);
        // setting TDV 2 to it's respective value in the test operand sequence...
        TDVSet(1, testValue2, operatingCycles, rollingAverage, tolerance);
        // adding TDV 1 and 2 & storing the result in TDV 3...
        TDVsAdd(0, 1, 2, operatingCycles, currOperationDuration, rollingAverage, tolerance);
        // tracking all TDVs & storing result to SD card...
        if (phaseLogSaveIters > 0)
        {
          startTime = micros();
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            timestampBuff[j][k][l] = micros() - startTime;
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
                cycleDiffBuff[m][j][k][l] = TDVGetCycles(m, operatingCycles, rollingAverage);
            }
          }
        }
      }
    }

    if (phaseLogSaveIters > 0)
    {
      SDCardInit();
      SDLogFileNew("log_phase_" + String(operatingCycles) + "_" + String(operationIdx) + "_" + String(i + 1) + ".txt");

      for (uint32_t j = 0; j < operationDurationTestNum; j++)
      {
        currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

        for (uint32_t k = 0; k < runsPerDurationTest; k++)
        {
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
              {
                data = String(operatingCycles) + "|" + 
                        String(operationIdx) + "|" +
                        String(currOperationDuration) + "|" +
                        String(i + 1) + "|" +
                        String(k + 1) + "|" +
                        String(m) + "|" +
                        String(TDVResultStatus[m]) + "|" +
                        String((uint32_t)round(TDVTargetValues[m] * operatingCycles)) + "|" +
                        String(l) + "|" + 
                        String(timestampBuff[j][k][l]) + "|" + 
                        String(cycleDiffBuff[m][j][k][l]);
                SDLogFileWriteLn(data);
              }
            }
          }
        }
      }

      SDLogFileClose();
      SDCardClose();
    }
  }
} //@\label{line:operationMcu_EvaluateTDVAddition_End}@

// function that evaluates the TDV inversion operation
// repeatedly executes the inversion operation over a set of pre-determined inputs & compares their expected outputs
inline void EvaluateTDVInversion(const uint32_t phaseLogSaveIters, const uint32_t operatingCycles, const uint32_t runsPerDurationTest, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_EvaluateTDVInversion_Start}@
{
  String data, dataHeader;
  uint32_t currOperationDuration, startTime;
  float testValue, tdv2ValueExpected;
  
  const uint8_t operationIdx = 2;

  // defining all test operand values...
  const uint32_t testValueNum = 31;
  const float testValues[testValueNum] = {
    0.2,
    0.22,
    0.24,
    0.26,
    0.28,
    0.3,
    0.32,
    0.34,
    0.36,
    0.38,
    0.4,
    0.42,
    0.44,
    0.46,
    0.48,
    0.5,
    0.52,
    0.54,
    0.56,
    0.58,
    0.6,
    0.62,
    0.64,
    0.66,
    0.68,
    0.7,
    0.72,
    0.74,
    0.76,
    0.78,
    0.8
  };

  const uint32_t operationDurationStart = OperationTestStarts[operationIdx];
  const uint32_t operationDurationBatchEnd = OperationTestBatchEnds[operationIdx];
  const uint32_t operationDurationStep = OperationTestSteps[operationIdx];
  const uint32_t operationDurationTestNum = floor((operationDurationBatchEnd - operationDurationStart) / operationDurationStep);
  
  uint32_t timestampBuff[operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];
  uint32_t cycleDiffBuff[TDVNum][operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];

  Serial.println("\n---- EVALUATING INVERSION ----");

  // running tests for all test operand values...
  for (uint32_t i = 0; i < testValueNum; i++)
  {
    testValue = testValues[i];
    tdv2ValueExpected = abs(1.0 - testValue);

    Serial.println("\n-- INVERSION TEST #" + String(i + 1) + " --");
    Serial.println("TDV 1 = " + String(testValue) + " | TDV 2 != TDV 1 = " + String(tdv2ValueExpected));
    delay(1000);
    
    TDVTrackingShow(0);
    TDVTrackingShow(1);
    TDVTrackingHide(2);
    TDVResultSet(0, 0);
    TDVResultSet(1, 2);
    TDVResultReset(2);

    for (uint32_t j = 0; j < operationDurationTestNum; j++)
    {
      currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

      for (uint32_t k = 0; k < runsPerDurationTest; k++)
      {
        // resetting all TDVs...
        TDVResetAll(operatingCycles, rollingAverage, tolerance);
        delay(RNGGet(1, 10));
        // setting TDV 1 to it's respective value in the test operand sequence...
        TDVSet(0, testValue, operatingCycles, rollingAverage, tolerance);
        // inverting TDV 1 & storing the result in TDV 2...
        TDVInvert(0, 1, operatingCycles, currOperationDuration, rollingAverage, tolerance);
        // tracking all TDVs & storing result to SD card...
        if (phaseLogSaveIters > 0)
        {
          startTime = micros();
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            timestampBuff[j][k][l] = micros() - startTime;
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
                cycleDiffBuff[m][j][k][l] = TDVGetCycles(m, operatingCycles, rollingAverage);
            }
          }
        }
      }
    }

    if (phaseLogSaveIters > 0)
    {
      SDCardInit();
      SDLogFileNew("log_phase_" + String(operatingCycles) + "_" + String(operationIdx) + "_" + String(i + 1) + ".txt");

      for (uint32_t j = 0; j < operationDurationTestNum; j++)
      {
        currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

        for (uint32_t k = 0; k < runsPerDurationTest; k++)
        {
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
              {
                data = String(operatingCycles) + "|" + 
                        String(operationIdx) + "|" +
                        String(currOperationDuration) + "|" +
                        String(i + 1) + "|" +
                        String(k + 1) + "|" +
                        String(m) + "|" +
                        String(TDVResultStatus[m]) + "|" +
                        String((uint32_t)round(TDVTargetValues[m] * operatingCycles)) + "|" +
                        String(l) + "|" + 
                        String(timestampBuff[j][k][l]) + "|" + 
                        String(cycleDiffBuff[m][j][k][l]);
                SDLogFileWriteLn(data);
              }
            }
          }
        }
      }

      SDLogFileClose();
      SDCardClose();
    }
  }
} //@\label{line:operationMcu_EvaluateTDVInversion_End}@

// function that evaluates the TDV copy operation
// repeatedly executes the copy operation over a set of pre-determined inputs & compares their expected outputs
inline void EvaluateTDVCopy(const uint32_t phaseLogSaveIters, const uint32_t operatingCycles, const uint32_t runsPerDurationTest, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_EvaluateTDVCopy_Start}@
{
  String data, dataHeader;
  uint32_t currOperationDuration, startTime;
  float testValue;

  const uint8_t operationIdx = 1;

  // defining all test operand values...
  const uint32_t testValueNum = 31;
  const float testValues[testValueNum] = {
    0.2,
    0.22,
    0.24,
    0.26,
    0.28,
    0.3,
    0.32,
    0.34,
    0.36,
    0.38,
    0.4,
    0.42,
    0.44,
    0.46,
    0.48,
    0.5,
    0.52,
    0.54,
    0.56,
    0.58,
    0.6,
    0.62,
    0.64,
    0.66,
    0.68,
    0.7,
    0.72,
    0.74,
    0.76,
    0.78,
    0.8
  };

  const uint32_t operationDurationStart = OperationTestStarts[operationIdx];
  const uint32_t operationDurationBatchEnd = OperationTestBatchEnds[operationIdx];
  const uint32_t operationDurationStep = OperationTestSteps[operationIdx];
  const uint32_t operationDurationTestNum = floor((operationDurationBatchEnd - operationDurationStart) / operationDurationStep);
  
  uint32_t timestampBuff[operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];
  uint32_t cycleDiffBuff[TDVNum][operationDurationTestNum][runsPerDurationTest][phaseLogSaveIters];

  Serial.println("\n---- EVALUATING COPY ----");

  // running tests for all test operand values...
  for (uint32_t i = 0; i < testValueNum; i++)
  {
    testValue = testValues[i];

    Serial.println("\n-- COPY TEST #" + String(i + 1) + " --");
    Serial.println("TDV 1 = " + String(testValue) + " | TDV 2 = TDV 1 = " + String(testValue));
    delay(1000);
    
    TDVTrackingShow(0);
    TDVTrackingShow(1);
    TDVTrackingHide(2);
    TDVResultSet(0, 0);
    TDVResultSet(1, 2);
    TDVResultReset(2);
    
    for (uint32_t j = 0; j < operationDurationTestNum; j++)
    {
      currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

      for (uint32_t k = 0; k < runsPerDurationTest; k++)
      {
        // resetting all TDVs...
        TDVResetAll(operatingCycles, rollingAverage, tolerance);
        delay(RNGGet(1, 10));
        // setting TDV 1 to it's respective value in the test operand sequence...
        TDVSet(0, testValue, operatingCycles, rollingAverage, tolerance);
        // copying TDV 1 & storing the result in TDV 2...
        TDVCopy(0, 1, operatingCycles, currOperationDuration, rollingAverage, tolerance);
        // tracking all TDVs & storing result to SD card...
        if (phaseLogSaveIters > 0)
        {
          startTime = micros();
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            timestampBuff[j][k][l] = micros() - startTime;
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
                cycleDiffBuff[m][j][k][l] = TDVGetCycles(m, operatingCycles, rollingAverage);
            }
          }
        }
      }
    }

    if (phaseLogSaveIters > 0)
    {
      SDCardInit();
      SDLogFileNew("log_phase_" + String(operatingCycles) + "_" + String(operationIdx) + "_" + String(i + 1) + ".txt");

      for (uint32_t j = 0; j < operationDurationTestNum; j++)
      {
        currOperationDuration = (operationDurationStep * (j + 1)) + operationDurationStart;

        for (uint32_t k = 0; k < runsPerDurationTest; k++)
        {
          for (uint32_t l = 0; l < phaseLogSaveIters; l++)
          {
            for (uint8_t m = 0; m < TDVNum; m++)
            {
              if (TDVTrackingMask[m])
              {
                data = String(operatingCycles) + "|" + 
                        String(operationIdx) + "|" +
                        String(currOperationDuration) + "|" +
                        String(i + 1) + "|" +
                        String(k + 1) + "|" +
                        String(m) + "|" +
                        String(TDVResultStatus[m]) + "|" +
                        String((uint32_t)round(TDVTargetValues[m] * operatingCycles)) + "|" +
                        String(l) + "|" + 
                        String(timestampBuff[j][k][l]) + "|" + 
                        String(cycleDiffBuff[m][j][k][l]);
                SDLogFileWriteLn(data);
              }
            }
          }
        }
      }

      SDLogFileClose();
      SDCardClose();
    }
  }
} //@\label{line:operationMcu_EvaluateTDVCopy_End}@

// function that evaluates the value setting of TDVs
// repeatedly sets all TDVs to set of pre-determined inputs & compares expected values
inline void EvaluateTDVSet(const uint32_t iters, const uint32_t operatingCycles, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_EvaluateTDVSet_Start}@
{
  String data;
  uint32_t startTime;
  float testValue;

  const uint8_t operationIdx = 0;

  // defining all test setting values...
  const uint32_t testValueNum = 9;
  const float testValues[testValueNum] = { //@\label{line:operationMcu_SetTestValues_Start}@
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9
  };  //@\label{line:operationMcu_SetTestValues_End}@

  uint32_t timestampBuff[TDVNum][iters];
  uint32_t cycleDiffBuff[TDVNum][iters];

  TDVsTrackingShowAll();
  TDVResultSetAll(2);

  // running tests for all test setting values...
  for (uint32_t i = 0; i < testValueNum; i++)
  {
    testValue = testValues[i];

    Serial.println("\n-- SETTING TEST #" + String(i + 1) + " --");
    Serial.println("TDVs = " + String(testValue));
    delay(1000);

    // resetting all TDVs...
    TDVResetAll(operatingCycles, rollingAverage, tolerance);
    delay(RNGGet(1, 10));

    for (uint8_t j = 0; j < TDVNum; j++)
    {
      // setting current TDV to the current value in test sequence...
      TDVSet(j, testValue, operatingCycles, rollingAverage, tolerance);
      // tracking all TDVs & storing result to SD card...
      if (iters > 0)
      {
        startTime = micros();
        for (uint32_t k = 0; k < iters; k++)
        {
          timestampBuff[j][k] = micros() - startTime;
          cycleDiffBuff[j][k] = TDVGetCycles(j, operatingCycles, rollingAverage);
        }
      }

      // displaying test results...
      //Serial.print("e: " + String(testValue));
      //Serial.println(" |r: " + String(runs));
    }

    if (iters > 0)
    {
      SDCardInit();
      SDLogFileNew("log_phase_" + String(operatingCycles) + "_" + String(operationIdx) + "_" + String(i + 1) + ".txt");

      for (uint32_t j = 0; j < iters; j++)
      {
        for (uint8_t k = 0; k < TDVNum; k++)
        {
          data = String(operatingCycles) + "|" + 
                  String(operationIdx) + "|1|" +
                  String(i + 1) + "|1|" +
                  String(k) + "|" +
                  String(TDVResultStatus[k]) + "|" +
                  String((uint32_t)round(TDVTargetValues[k] * operatingCycles)) + "|" +
                  String(j) + "|" + 
                  String(timestampBuff[k][j]) + "|" + 
                  String(cycleDiffBuff[k][j]);
          SDLogFileWriteLn(data);
        }
      }

      SDLogFileClose();
      SDCardClose();
    }
  }
} //@\label{line:operationMcu_EvaluateTDVSet_End}@

// function that evaluates the oscillator operating frequencies
// measures the operating frequencies of all oscillators for a pre-determined duration of time
inline void EvaluateOscillatorFrequencies(const uint32_t iters, const uint32_t operatingCycles, const uint32_t rollingAverage) //@\label{line:operationMcu_EvaluateOscillatorFrequencies_Start}@
{
  Serial.println("\n---- TESTING FREQUENCIES ----\n");

  // waiting for 1 second...
  delay(1000);
  // tracking high & low duty cycle durations of all oscillators...
  OscillatorTrackFrequenciesAll(operatingCycles, iters, micros(), rollingAverage, "log_freq_" + String(operatingCycles) + ".txt");
} //@\label{line:operationMcu_EvaluateOscillatorFrequencies_End}@

//// TDV FUNCTIONS ////

// wrapper function for TDV subtraction 
// performs the operation for a specified number of iterations
// returns the number of iterations the TDV operation was executed for
inline uint32_t TDVsSubtract(const uint8_t shiftingTdvIdx, const uint8_t stationaryTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVsSubtract_Start}@
{
  uint32_t runs;
  float result;

  // setting the expected TDV values...
  TDVTargetValues[resultTdvIdx] = TDVTargetValues[stationaryTdvIdx] - TDVTargetValues[shiftingTdvIdx];
  
  runs = 0;
  do
  {
    if (runs >= 1000000)
      break;
    runs++;
    // execute one TDV operation iteration...
    TDVsSubtractCycles(shiftingTdvIdx, stationaryTdvIdx, resultTdvIdx, operatingCycles, duration);
    result = TDVGet(resultTdvIdx, operatingCycles, rollingAverage);
  } while ((result < tolerance) || (result > (1.0 - tolerance)));

  return runs;
} //@\label{line:operationMcu_TDVsSubtract_End}@

// function that performs the TDV subtraction operation for a single iteration
FASTRUN __attribute__((noinline)) void TDVsSubtractCycles(const uint8_t shiftingTdvIdx, const uint8_t stationaryTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration) //@\label{line:operationMcu_TDVsSubtractCycles_Start}@
{
  TDVUnpause(shiftingTdvIdx);
  TDVUnpause(stationaryTdvIdx);
  TDVUnpause(resultTdvIdx);

  const uint32_t startTime = micros();
  while ((micros() - startTime) <= duration)
  {
    // alignment operation step...
    {
      // pausing the shifting TDV
      // if the XOR between the shifting & stationary TDVs' reference clocks is TRUE...
      LogicGateXOR(TDVGetRef(shiftingTdvIdx, false), TDVGetRef(stationaryTdvIdx, false)) 
      ? TDVPause(shiftingTdvIdx) : TDVUnpause(shiftingTdvIdx);
    }

    // construction operation step...
    {
      // pausing the result TDV's value clock 
      // if the XOR between the stationary & result TDVs' value clocks is TRUE...
      LogicGateXOR(TDVGetVal(stationaryTdvIdx, false), TDVGetVal(resultTdvIdx, false)) 
      ? TDVPauseVal(resultTdvIdx) : TDVUnpauseVal(resultTdvIdx);

      // pausing the result TDV's reference clock 
      // if the XOR between the shifting TDV's value clock & the result TDV's reference clock is TRUE...
      LogicGateXOR(TDVGetVal(shiftingTdvIdx, false), TDVGetRef(resultTdvIdx, false)) 
      ? TDVPauseRef(resultTdvIdx) : TDVUnpauseRef(resultTdvIdx);
    }
  }

  TDVUnpause(shiftingTdvIdx);
  TDVUnpause(stationaryTdvIdx);
  TDVUnpause(resultTdvIdx);
} //@\label{line:operationMcu_TDVsSubtractCycles_End}@

// wrapper function for TDV addition 
// performs the operation for a specified number of iterations
// returns the number of iterations the TDV operation was executed for
inline uint32_t TDVsAdd(const uint8_t shiftingTdvIdx, const uint8_t stationaryTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVsAdd_Start}@
{
  uint32_t runs;
  float result;

  // setting the expected TDV values...
  TDVTargetValues[resultTdvIdx] = TDVTargetValues[shiftingTdvIdx] + TDVTargetValues[stationaryTdvIdx];
  
  runs = 0;
  do
  {
    if (runs >= 1000000)
      break;
    runs++;
    // execute one TDV operation iteration...
    TDVsAddCycles(shiftingTdvIdx, stationaryTdvIdx, resultTdvIdx, operatingCycles, duration);
    result = TDVGet(resultTdvIdx, operatingCycles, rollingAverage);
  } while ((result < tolerance) || (result > (1.0 - tolerance)));

  return runs;
} //@\label{line:operationMcu_TDVsAdd_End}@

// function that performs the TDV addition operation for a single iteration
FASTRUN __attribute__((noinline)) void TDVsAddCycles(const uint8_t shiftingTdvIdx, const uint8_t stationaryTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration) //@\label{line:operationMcu_TDVsAddCycles_Start}@
{
  TDVUnpause(shiftingTdvIdx);
  TDVUnpause(stationaryTdvIdx);
  TDVUnpause(resultTdvIdx);

  const uint32_t startTime = micros();
  while ((micros() - startTime) <= duration)
  {
    // alignment operation step...
    {
      // pausing the shifting TDV
      // if the XOR between the shifting TDV's value clock & the stationary TDV's reference clock is TRUE...
      LogicGateXOR(TDVGetVal(shiftingTdvIdx, false), TDVGetRef(stationaryTdvIdx, false)) 
      ? TDVPause(shiftingTdvIdx) : TDVUnpause(shiftingTdvIdx);
    }

    // construction operation step...
    {
      // pausing the result TDV's value clock 
      // if the XOR between the stationary & result TDVs' value clocks is TRUE...
      LogicGateXOR(TDVGetVal(stationaryTdvIdx, false), TDVGetVal(resultTdvIdx, false)) 
      ? TDVPauseVal(resultTdvIdx) : TDVUnpauseVal(resultTdvIdx);

      // pausing the result TDV's reference clock 
      // if the XOR between the shifting & result TDVs' reference clocks is TRUE...
      LogicGateXOR(TDVGetRef(shiftingTdvIdx, false), TDVGetRef(resultTdvIdx, false)) 
      ? TDVPauseRef(resultTdvIdx) : TDVUnpauseRef(resultTdvIdx);
    }
  }

  TDVUnpause(shiftingTdvIdx);
  TDVUnpause(stationaryTdvIdx);
  TDVUnpause(resultTdvIdx);
} //@\label{line:operationMcu_TDVsAddCycles_End}@

// wrapper function for TDV inversion 
// performs the operation for a specified number of iterations
// returns the number of iterations the TDV operation was executed for
inline uint32_t TDVInvert(const uint8_t operandTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVInvert_Start}@
{
  uint32_t runs;
  float result;

  // setting the expected TDV values...
  TDVTargetValues[resultTdvIdx] = abs(1.0 - TDVTargetValues[operandTdvIdx]);
  
  runs = 0;
  do
  {
    if (runs >= 1000000)
      break;
    runs++;
    // execute one TDV operation iteration...
    TDVInvertCycles(operandTdvIdx, resultTdvIdx, operatingCycles, duration);
    result = TDVGet(resultTdvIdx, operatingCycles, rollingAverage);
  } while ((result < tolerance) || (result > (1.0 - tolerance)));

  return runs;
} //@\label{line:operationMcu_TDVInvert_End}@

// function that performs the TDV inversion operation for a single iteration
FASTRUN __attribute__((noinline)) void TDVInvertCycles(const uint8_t operandTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration) //@\label{line:operationMcu_TDVInvertCycles_Start}@
{
  TDVUnpause(operandTdvIdx);
  TDVUnpause(resultTdvIdx);

  const uint32_t startTime = micros();
  while ((micros() - startTime) <= duration)
  {
    // operation step...
    {
      // pausing the result TDV's value clock 
      // if the XOR between the operand TDV's inverted reference clock & the result TDV's value clock is TRUE...
      LogicGateXOR(TDVGetRef(operandTdvIdx, true), TDVGetVal(resultTdvIdx, false)) 
      ? TDVPauseVal(resultTdvIdx) : TDVUnpauseVal(resultTdvIdx);

      // pausing the result TDV's reference clock 
      // if the XOR between the operand TDV's value clock & the result TDV's reference clock is TRUE...
      LogicGateXOR(TDVGetVal(operandTdvIdx, false), TDVGetRef(resultTdvIdx, false)) 
      ? TDVPauseRef(resultTdvIdx) : TDVUnpauseRef(resultTdvIdx);
    }
  }

  TDVUnpause(operandTdvIdx);
  TDVUnpause(resultTdvIdx);
} //@\label{line:operationMcu_TDVInvertCycles_End}@

// wrapper function for TDV copy 
// performs the operation for a specified number of iterations
// returns the number of iterations the TDV operation was executed for
inline uint32_t TDVCopy(const uint8_t operandTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVCopy_Start}@
{
  uint32_t runs;
  float result;

  // setting the expected TDV values...
  TDVTargetValues[resultTdvIdx] = TDVTargetValues[operandTdvIdx];

  runs = 0;
  do
  {
    if (runs >= 1000000)
      break;
    runs++;
    // execute one TDV operation iteration...
    TDVCopyCycles(operandTdvIdx, resultTdvIdx, operatingCycles, duration);
    result = TDVGet(resultTdvIdx, operatingCycles, rollingAverage);
  } while ((result < tolerance) || (result > (1.0 - tolerance)));

  return runs;
} //@\label{line:operationMcu_TDVCopy_End}@

// function that performs the TDV copy operation for a single iteration
FASTRUN __attribute__((noinline)) void TDVCopyCycles(const uint8_t operandTdvIdx, const uint8_t resultTdvIdx, const uint32_t operatingCycles, const uint32_t duration) //@\label{line:operationMcu_TDVCopyCycles_Start}@
{
  TDVUnpause(operandTdvIdx);
  TDVUnpause(resultTdvIdx);

  const uint32_t startTime = micros();
  while ((micros() - startTime) <= duration)
  {
    // operation step...
    {
      // pausing the result TDV's value clock 
      // if the XOR between the operand & result TDVs' value clocks is TRUE...
      LogicGateXOR(TDVGetVal(operandTdvIdx, false), TDVGetVal(resultTdvIdx, false)) 
      ? TDVPauseVal(resultTdvIdx) : TDVUnpauseVal(resultTdvIdx);

      // pausing the result TDV's reference clock 
      // if the XOR between the operand & result TDVs' reference clocks is TRUE...
      LogicGateXOR(TDVGetRef(operandTdvIdx, false), TDVGetRef(resultTdvIdx, false)) 
      ? TDVPauseRef(resultTdvIdx) : TDVUnpauseRef(resultTdvIdx);
    }
  }

  TDVUnpause(operandTdvIdx);
  TDVUnpause(resultTdvIdx);
} //@\label{line:operationMcu_TDVCopyCycles_End}@

// wrapper function for setting of all TDVs in the system 
// sets TDVs to 0 for a specified number of cycles
inline void TDVResetAll(const uint32_t operatingCycles, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVResetAll_Start}@
{
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVReset(i, operatingCycles, rollingAverage, tolerance);
  }
} //@\label{line:operationMcu_TDVResetAll_End}@

// wrapper function for setting of a single TDV 
// sets TDV to 0 for a specified number of cycles
// returns the number of iterations the TDV was reset for
inline uint32_t TDVReset(const uint8_t tdvIdx, const uint32_t operatingCycles, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVReset_Start}@
{
  return TDVSet(tdvIdx, 0.0, operatingCycles, rollingAverage, tolerance);
} //@\label{line:operationMcu_TDVReset_End}@

// wrapper function for setting of a single TDV 
// sets TDV to the provided value for a specified number of iterations
// returns the number of iterations the TDV was set for
inline uint32_t TDVSet(const uint8_t tdvIdx, float value, const uint32_t operatingCycles, const uint32_t rollingAverage, const float tolerance) //@\label{line:operationMcu_TDVSet_Start}@
{
  uint32_t runs;

  // setting the expected TDV value...
  if (value > 1.0)
    value = 1.0;
  else if (value < 0.0)
    value = 0.0;
  TDVTargetValues[tdvIdx] = value;

  runs = 0;
  do
  {
    if (runs >= 1000000)
      break;
    runs++;
    // execute one TDV setting iteration...
    TDVSetCycles(tdvIdx, (uint32_t)round(value * operatingCycles), operatingCycles);
  } while (!PhaseValuesCheckTolerance(TDVGet(tdvIdx, operatingCycles, rollingAverage), value, tolerance));

  return runs;
} //@\label{line:operationMcu_TDVSet_End}@

// function that sets an TDV to the provided value for a single iteration
// accepts the set value as number of CPU cycles
FASTRUN __attribute__((noinline)) void TDVSetCycles(const uint8_t tdvIdx, const uint32_t setCycles, const uint32_t operatingCycles) //@\label{line:operationMcu_TDVSetCycles_Start}@
{
  volatile bool checkState, prevCheckState;
  bool firstIterGuard;
  uint32_t startCycles, elapsedCycles;

  TDVUnpause(tdvIdx);

  // running the setting for a number of iterations...
  {
    // waiting for rising edge of reference clock
    // while pausing the value clock if it's currently active...
    firstIterGuard = false;
    checkState = TDVGetRef(tdvIdx, false);
    do
    {
      if (firstIterGuard)
      {
        TDVGetVal(tdvIdx, false) ? 
        TDVPauseVal(tdvIdx) : TDVUnpauseVal(tdvIdx);
      }
      firstIterGuard = true;

      prevCheckState = checkState;
      checkState = TDVGetRef(tdvIdx, false);
    } while (!(checkState && (prevCheckState != checkState)));

    // waiting for iters of the set value in CPU cycles
    // while pausing the value clock if it's currently active...
    firstIterGuard = false;
    startCycles = CPUCyclesGet();
    do
    {
      if (firstIterGuard)
      {
        TDVGetVal(tdvIdx, false) ? 
        TDVPauseVal(tdvIdx) : TDVUnpauseVal(tdvIdx);
      }
      firstIterGuard = true;

      elapsedCycles = CPUCyclesGet() - startCycles;
    } while (elapsedCycles <= setCycles);

    // waiting for duration of high duty cycle operation duration
    // while pausing the value clock if it's not currently active...
    firstIterGuard = false;
    startCycles = CPUCyclesGet();
    do
    {
      if (firstIterGuard)
      {
        TDVGetVal(tdvIdx, false) ? 
        TDVUnpauseVal(tdvIdx) : TDVPauseVal(tdvIdx);
      }
      firstIterGuard = true;

      elapsedCycles = CPUCyclesGet() - startCycles;
    } while (elapsedCycles <= operatingCycles);
  }

  TDVUnpause(tdvIdx);
} //@\label{line:operationMcu_TDVSetCycles_End}@

// wrapper function for reading of a single TDV value 
// returns the read value as a range between 0.0 & 2.0
// 0.0 represents 0°, 1.0 represents 180°, 2.0 represents 360°
inline float TDVGet(const uint8_t tdvIdx, const uint32_t operatingCycles, const uint32_t rollingAverage) //@\label{line:operationMcu_TDVGet_Start}@
{
  float value;

  // measuring TDV phase difference in CPU cycles, and converting it to a range between 0.0 & 2.0...
  float avg = 0.0;
  
  for (uint32_t i = 0; i < rollingAverage; i++)
  {
    value = static_cast<float>(TDVGetCycles(tdvIdx, operatingCycles, rollingAverage)) / static_cast<float>(operatingCycles);
    avg += value;
  }
  
  return (avg / rollingAverage);
} //@\label{line:operationMcu_TDVGet_End}@

// function that reads the value of an TDV for a single iteration
// returns the read value as the number of CPU cycles
FASTRUN __attribute__((noinline)) uint32_t TDVGetCycles(const uint8_t tdvIdx, const uint32_t operatingCycles, const uint32_t rollingAverage) //@\label{line:operationMcu_TDVGetCycles_Start}@
{
  volatile bool checkState, prevCheckState;
  uint32_t startCycles, elapsedCycles;

  TDVUnpause(tdvIdx);

  // waiting for rising edge of reference clock...
  checkState = TDVGetRef(tdvIdx, false);
  do
  {
    prevCheckState = checkState;
    checkState = TDVGetRef(tdvIdx, false);
  } while (!(checkState && (prevCheckState != checkState)));

  // waiting for rising edge of value clock, or the maximum (360°)...
  startCycles = CPUCyclesGet();
  checkState = TDVGetVal(tdvIdx, false);
  do
  {
    elapsedCycles = CPUCyclesGet() - startCycles;
    prevCheckState = checkState;
    checkState = TDVGetVal(tdvIdx, false);
  } while (!(checkState && (prevCheckState != checkState)) && (elapsedCycles <= (operatingCycles * 2)));

  // saving the measured value...
  elapsedCycles = CPUCyclesGet() - startCycles;

  TDVUnpause(tdvIdx);

  return elapsedCycles;
} //@\label{line:operationMcu_TDVGetCycles_End}@

// function that gets the instantaneous state of a given TDV's value clock
inline volatile bool TDVGetVal(const uint8_t tdvIdx, const bool invert) //@\label{line:operationMcu_TDVGetVal_Start}@
{
  return OscillatorGetState(TDVOscillators[tdvIdx][0], invert);
} //@\label{line:operationMcu_TDVGetVal_End}@

// function that gets the instantaneous state of a given TDV's reference clock
inline volatile bool TDVGetRef(const uint8_t tdvIdx, const bool invert) //@\label{line:operationMcu_TDVGetRef_Start}@
{
  return OscillatorGetState(TDVOscillators[tdvIdx][1], invert);
} //@\label{line:operationMcu_TDVGetRef_End}@

// function that pauses both the value & reference clocks of a given TDV
inline void TDVPause(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVPause_Start}@
{
  TDVPauseVal(tdvIdx);
  TDVPauseRef(tdvIdx);
} //@\label{line:operationMcu_TDVPause_End}@

// function that pauses the value clock of a given TDV
inline void TDVPauseVal(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVPauseVal_Start}@
{
  OscillatorPause(TDVOscillators[tdvIdx][0]);
} //@\label{line:operationMcu_TDVPauseVal_End}@

// function that pauses the reference clock of a given TDV
inline void TDVPauseRef(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVPauseRef_Start}@
{
  OscillatorPause(TDVOscillators[tdvIdx][1]);
} //@\label{line:operationMcu_TDVPauseRef_End}@

// function that unpauses both the value & reference clocks of a given TDV
inline void TDVUnpause(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVUnpause_Start}@
{
  TDVUnpauseVal(tdvIdx);
  TDVUnpauseRef(tdvIdx);
} //@\label{line:operationMcu_TDVUnpause_End}@

// function that unpauses the value clock of a given TDV
inline void TDVUnpauseVal(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVUnpauseVal_Start}@
{
  OscillatorUnpause(TDVOscillators[tdvIdx][0]);
} //@\label{line:operationMcu_TDVUnpauseVal_End}@

// function that unpauses the reference clock of a given TDV
inline void TDVUnpauseRef(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVUnpauseRef_Start}@
{
  OscillatorUnpause(TDVOscillators[tdvIdx][1]);
} //@\label{line:operationMcu_TDVUnpauseRef_End}@

// function that enables both the value & reference clocks of a given TDV
inline void TDVEnable(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVEnable_Start}@
{
  TDVEnableVal(tdvIdx);
  TDVEnableRef(tdvIdx);
} //@\label{line:operationMcu_TDVEnable_End}@

// function that enables the value clock of a given TDV
inline void TDVEnableVal(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVEnableVal_Start}@
{
  OscillatorEnable(TDVOscillators[tdvIdx][0]);
} //@\label{line:operationMcu_TDVEnableVal_End}@

// function that enables the reference clock of a given TDV
inline void TDVEnableRef(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVEnableRef_Start}@
{
  OscillatorEnable(TDVOscillators[tdvIdx][1]);
} //@\label{line:operationMcu_TDVEnableRef_End}@

// function that disables both the value & reference clocks of a given TDV
inline void TDVDisable(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVDisable_Start}@
{
  TDVDisableVal(tdvIdx);
  TDVDisableRef(tdvIdx);
} //@\label{line:operationMcu_TDVDisable_End}@

// function that disables the value clock of a given TDV
inline void TDVDisableVal(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVDisableVal_Start}@
{
  OscillatorDisable(TDVOscillators[tdvIdx][0]);
} //@\label{line:operationMcu_TDVDisableVal_End}@

// function that disables the reference clock of a given TDV
inline void TDVDisableRef(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVDisableRef_Start}@
{
  OscillatorDisable(TDVOscillators[tdvIdx][1]);
} //@\label{line:operationMcu_TDVDisableRef_End}@

//// OSCILLATOR FUNCTIONS ////

// function that measures a single duty cycle duration for a given oscillator
FASTRUN __attribute__((noinline)) uint32_t OscillatorGetCycles(const uint8_t oscillatorIdx, const bool invert, const uint32_t rollingAverage) //@\label{line:operationMcu_OscillatorGetCycles_Start}@
{
  uint32_t startCycles, elapsedCycles, measuredCycles;
  volatile bool checkState, prevCheckState;

  measuredCycles = 0;

  // measuring the duty cycle for number of rolling averages...
  for (uint32_t i = 0; i < rollingAverage; i++)
  {
    // waiting for rising edge...
    checkState = OscillatorGetState(oscillatorIdx, invert);
    do
    {
      prevCheckState = checkState;
      checkState = OscillatorGetState(oscillatorIdx, invert);
    } while (!(checkState && (prevCheckState != checkState)));

    // waiting for falling edge, while measuring cycles...
    startCycles = CPUCyclesGet();
    checkState = OscillatorGetState(oscillatorIdx, invert);
    do
    {
      prevCheckState = checkState;
      checkState = OscillatorGetState(oscillatorIdx, invert);
    } while (!(!checkState && (prevCheckState != checkState)));

    // saving the measured cycles...
    elapsedCycles = CPUCyclesGet() - startCycles;
    if (i == 0)
      measuredCycles = elapsedCycles;
    else
      measuredCycles = (measuredCycles + elapsedCycles) / 2;
  }

  return measuredCycles;
} //@\label{line:operationMcu_OscillatorGetCycles_End}@

// function that reads the instantaneous state of a given oscillator
FASTRUN __attribute__((noinline)) volatile bool OscillatorGetState(const uint8_t oscillatorIdx, const bool invert) //@\label{line:operationMcu_OscillatorGetState_Start}@
{
  return invert ? !DigitalPinGet(PINS_SIGNAL[oscillatorIdx]) : DigitalPinGet(PINS_SIGNAL[oscillatorIdx]);
} //@\label{line:operationMcu_OscillatorGetState_End}@

// function that pauses a given oscillator
FASTRUN __attribute__((noinline)) void OscillatorPause(const uint8_t oscillatorIdx) //@\label{line:operationMcu_OscillatorPause_Start}@
{
  DigitalPinSet(PINS_PAUSE[oscillatorIdx], LOW);
} //@\label{line:operationMcu_OscillatorPause_End}@

// function that unpauses a given oscillator
FASTRUN __attribute__((noinline)) void OscillatorUnpause(const uint8_t oscillatorIdx) //@\label{line:operationMcu_OscillatorUnpause_Start}@
{
  DigitalPinSet(PINS_PAUSE[oscillatorIdx], HIGH);
} //@\label{line:operationMcu_OscillatorUnpause_End}@

// function that enables a given oscillator
FASTRUN __attribute__((noinline)) void OscillatorEnable(const uint8_t oscillatorIdx) //@\label{line:operationMcu_OscillatorEnable_Start}@
{
  DigitalPinSet(PINS_ENABLE[oscillatorIdx], HIGH);
} //@\label{line:operationMcu_OscillatorEnable_End}@

// function that disables a given oscillator
FASTRUN __attribute__((noinline)) void OscillatorDisable(const uint8_t oscillatorIdx) //@\label{line:operationMcu_OscillatorDisable_Start}@
{
  DigitalPinSet(PINS_ENABLE[oscillatorIdx], LOW);
} //@\label{line:operationMcu_OscillatorDisable_End}@

//// EVALUATION FUNCTIONS ////

inline void TDVResultSetAll(uint8_t status)
{
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVResultSet(i, status);
  }
}

inline void TDVResultSet(const uint8_t tdvIdx, uint8_t status)
{
  TDVResultStatus[tdvIdx] = status;
}

inline void TDVResultResetAll()
{
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVResultReset(i);
  }
}

inline void TDVResultReset(const uint8_t tdvIdx)
{
  TDVResultStatus[tdvIdx] = 0;
}

// function that hides all TDVs from subsequent TDV value tracking sessions
inline void TDVsTrackingHideAll() //@\label{line:operationMcu_TDVsTrackingHideAll_Start}@
{
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVTrackingHide(i);
  }
} //@\label{line:operationMcu_TDVsTrackingHideAll_End}@

// function that hides a given TDV from subsequent TDV value tracking sessions
inline void TDVTrackingHide(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVTrackingHide_Start}@
{
  TDVTrackingMask[tdvIdx] = false;
} //@\label{line:operationMcu_TDVTrackingHide_End}@

// function that shows all TDVs in subsequent TDV value tracking sessions
inline void TDVsTrackingShowAll() //@\label{line:operationMcu_TDVsTrackingShowAll_Start}@
{
  for (uint8_t i = 0; i < TDVNum; i++)
  {
    TDVTrackingShow(i);
  }
} //@\label{line:operationMcu_TDVsTrackingShowAll_End}@

// function that shows a given TDV in subsequent TDV value tracking sessions
inline void TDVTrackingShow(const uint8_t tdvIdx) //@\label{line:operationMcu_TDVTrackingShow_Start}@
{
  TDVTrackingMask[tdvIdx] = true;
} //@\label{line:operationMcu_TDVTrackingShow_End}@

// function that tracks the high & low duty cycle durations of all oscillators in the system over a given duration of time
// saves data to a specified file on an SD card
inline void OscillatorTrackFrequenciesAll(const uint32_t operatingCycles, const uint32_t iters, const uint32_t startTimeMicros, const uint32_t rollingAverage, const String logFilePath) //@\label{line:operationMcu_OscillatorTrackFrequenciesAll_Start}@
{
  String data;

  // declaring buffers for saving all measured data...
  uint32_t timestampsBuff[iters];
  uint32_t cyclesHighBuff[iters][OscillatorNum];
  uint32_t cyclesLowBuff[iters][OscillatorNum];

  // tracking all oscillator operating duty cycle durations over a number of iterations...
  for (uint32_t i = 0; i < iters; i++)
  {
    timestampsBuff[i] = micros() - startTimeMicros;

    for (uint8_t j = 0; j < OscillatorNum; j++)
    {
      cyclesHighBuff[i][j] = OscillatorGetCycles(j, false, rollingAverage);
      cyclesLowBuff[i][j] = OscillatorGetCycles(j, true, rollingAverage);
    }
  }

  // saving measured duty cycle data...
  {
    SDCardInit();
    SDLogFileNew(logFilePath);
    for (uint32_t i = 0; i < iters; i++)
    {
      for (uint8_t j = 0; j < OscillatorNum; j++)
      {
        data = String(operatingCycles) + "|" + 
                      String(j) + "|0|0|" + 
                      String(i) + "|" + 
                      String(timestampsBuff[i]) + "|" + 
                      String(cyclesHighBuff[i][j]);
        SDLogFileWriteLn(data);

        data = String(operatingCycles) + "|" + 
                      String(j) + "|1|0|" + 
                      String(i) + "|" + 
                      String(timestampsBuff[i]) + "|" + 
                      String(cyclesLowBuff[i][j]);
        SDLogFileWriteLn(data);
      }
    }
    SDLogFileClose();
    SDCardClose();
  }
} //@\label{line:operationMcu_OscillatorTrackFrequenciesAll_End}@

//// LOGIC GATE FUNCTIONS ////

// function that simulates a digital exclusive-OR (XOR) logic gate
inline bool LogicGateXOR(const bool inputA, const bool inputB) //@\label{line:operationMcu_LogicGateXOR_Start}@
{
  return (inputA != inputB);
} //@\label{line:operationMcu_LogicGateXOR_End}@

//// SD CARD FUNCTIONS ////

// function that creates a new log file on the SD card with the provided file path
inline void SDLogFileNew(const String filePath) //@\label{line:operationMcu_SDLogFileNew_Start}@
{
  LogFile = SD.sdfs.open(filePath.c_str(), O_WRITE | O_CREAT | O_TRUNC);
  SDLogFileWriteLn("---- START ----\n");
} //@\label{line:operationMcu_SDLogFileNew_End}@

// function that writes a single line to the currently-opened log file on the SD card
inline void SDLogFileWriteLn(const String data) //@\label{line:operationMcu_SDLogFileWriteLn_Start}@
{
  LogFile.println(data);
} //@\label{line:operationMcu_SDLogFileWriteLn_End}@

// function that closes & saves the currently-opened log file on the SD card
inline void SDLogFileClose() //@\label{line:operationMcu_SDLogFileClose_Start}@
{
  LogFile.flush();
  LogFile.close();
} //@\label{line:operationMcu_SDLogFileClose_End}@

// function that initializes a connected SD card
inline void SDCardInit() //@\label{line:operationMcu_SDCardInit_Start}@
{
  while (!SD.sdfs.begin(SDCardConfig))
  {
    Serial.println("unable to find SD card!");
    delay(500);
  }
} //@\label{line:operationMcu_SDCardInit_End}@

// function that closes a connected SD card
inline void SDCardClose() //@\label{line:operationMcu_SDCardClose_Start}@
{
  SD.sdfs.end();
} //@\label{line:operationMcu_SDCardClose_End}@

//// CYCLE COUNTER FUNCTIONS ////

// function that provides the current state of the MCU's internal CPU cycle counter register
inline volatile uint32_t CPUCyclesGet() //@\label{line:operationMcu_CPUCyclesGet_Start}@
{
  return ARM_DWT_CYCCNT;
} //@\label{line:operationMcu_CPUCyclesGet_End}@

// function that initializes the MCU's internal CPU cycle counter register
inline void CPUCyclesInit() //@\label{line:operationMcu_CPUCyclesInit_Start}@
{
  ARM_DEMCR |= ARM_DEMCR_TRCENA;
  ARM_DWT_CTRL |= ARM_DWT_CTRL_CYCCNTENA;
  ARM_DWT_CYCCNT = 0;
} //@\label{line:operationMcu_CPUCyclesInit_End}@

//// RANDOM NUMBER GENERATOR FUNCTIONS ////

// function that retrieves a single decimal number from the psuedo-random number generator
inline float RNGGet(const float min, const float max, const uint32_t factor) //@\label{line:operationMcu_RNGGet_Start}@
{
  return (RNGGet(min * static_cast<float>(factor), max * static_cast<float>(factor)) / static_cast<float>(factor));
}

// function that retrieves a single unsigned 32-bit integer number from the psuedo-random number generator
inline uint32_t RNGGet(const uint32_t min, const uint32_t max)
{
  return random(min, max);
} //@\label{line:operationMcu_RNGGet_End}@

// function that initializes the psuedo-random number generator
inline void RNGInit() //@\label{line:operationMcu_RNGInit_Start}@
{
  randomSeed(analogRead(PIN_RNG));
} //@\label{line:operationMcu_RNGInit_End}@

//// SUPPORT FUNCTIONS ////

// function that checks whether the two provided phase decimal values are within the provided tolerance of each other
inline bool PhaseValuesCheckTolerance(float valueA, float valueB, const float tolerance) //@\label{line:operationMcu_PhaseValuesCheckTolerance_Start}@
{
  if ((valueA <= 2.0) && (valueA > (2.0 - tolerance)))
    valueA -= 2.0;
  if ((valueB <= 2.0) && (valueB > (2.0 - tolerance)))
    valueB -= 2.0;
  return (abs(valueA - valueB) < tolerance);
} //@\label{line:operationMcu_PhaseValuesCheckTolerance_End}@

// function that converts an TDV phase difference value from the decimal representation (0.0 - 2.0) to the degree representation (0° - 360°)
inline float PhaseValueDecimalToDegrees(const float decimal) //@\label{line:operationMcu_PhaseValueDecimalToDegrees_Start}@
{
  return (decimal / 1.0) * 180;
} //@\label{line:operationMcu_PhaseValueDecimalToDegrees_End}@

// function that sets a single digital IO pin to the provided digital value
inline void DigitalPinSet(const uint8_t pin, const bool value) //@\label{line:operationMcu_DigitalPinSet_Start}@
{
  digitalWrite(pin, value);
} //@\label{line:operationMcu_DigitalPinSet_End}@

// function that reads a single digital IO pin
inline bool DigitalPinGet(const uint8_t pin) //@\label{line:operationMcu_DigitalPinGet_Start}@
{
  return digitalReadFast(pin);
} //@\label{line:operationMcu_DigitalPinGet_End}@

// function that initializes a single digital IO pin
inline void DigitalPinInit(const uint8_t pin, const uint8_t mode) //@\label{line:operationMcu_DigitalPinInit_Start}@
{
  pinMode(pin, mode);
} //@\label{line:operationMcu_DigitalPinInit_End}@

// function that gets the absolute difference between two 32-bit unsigned integer numbers
inline uint32_t UnsignedGetDifference(const uint32_t valueA, const uint32_t valueB) //@\label{line:operationMcu_UnsignedGetDifference_Start}@
{
  return (valueB > valueA) ? (valueB - valueA) : (valueA - valueB);
} //@\label{line:operationMcu_UnsignedGetDifference_End}@

// function that subtracts two 32-bit unsigned integer numbers
// truncates result to 0 if an overflow is detected
inline uint32_t SubtractUnsigned(const uint32_t numA, const uint32_t numB) //@\label{line:operationMcu_SubtractUnsigned_Start}@
{
  return (numB > numA) ? 0 : (numA - numB);
} //@\label{line:operationMcu_SubtractUnsigned_End}@